baseURL: https://open.id.au/
disablePathToLower: true
languageCode: en
title: Tim Abdiukov
author: Tim Abdiukov

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: friendly
    lineNos: false

paginate: 100

# vitae theme settings
menu:
  main:
    - name: posts
      url: "/post"
      weight: 10
    - name: reports
      url: "/report"
      weight: 20

theme: hugo-vitae-nord
favicon: true

copyright: "Personal blog of Tim Abdiukov"


# social links

params:
  social:
    - name: Github
      icon: fab fa-github
      url: "https://github.com/TAbdiukov"
    - name: LinkedIn
      icon: fab fa-linkedin
      url: "https://linkedin.com/in/tim-abdiukov"
    - name: RSS
      icon: fas fa-rss
      url: /index.xml
  thumbnails:
    enabled: true
  readtime:
    enableListing: true
